######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 5 22:36:03 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/data.h src/input.h src/output.h src/setup.h src/solve.h
SOURCES += src/FlowSim.cpp \
           src/input.cpp \
           src/output.cpp \
           src/setup.cpp \
           src/solve.cpp
